version: '3'
services:

  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 7070
      MYSQL_DATABASE: smart_parking_team2
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db_data:/var/lib/mysql

  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    depends_on:
      - mariadb
    restart: always
    environment:
      SMART_PARKING_DB_URL: jdbc:mariadb://mariadb:3306/smart_parking_team2
      SMART_PARKING_DB_USER: admin
      SMART_PARKING_DB_PASSWORD: 1234